name: Build and deploy sanity studio to prod
on:
  push:
    branches: [main]

# FIXME: Legg til docker layer caching, f.eks. https://github.com/marketplace/actions/build-docker-images-using-cache
jobs:
  build_and_deploy:
    name: Build and deploy to prod
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}-sanity
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install Sanity dependencies
        working-directory: ./sanity
        run: npm ci
      - name: Build Sanity
        working-directory: ./sanity
        run: SANITY_STUDIO_API_DATASET=production npm run build
      - name: Login to GitHub package registry
        run: |
          echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_REPOSITORY} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create artifact version
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-artifact-version@master
      - name: Get complete tag
        run: |
          echo "COMPLETE_TAG=prod-gcp-$( date +%s )-${{ steps.artifact-version.outputs.version }}" >> $GITHUB_ENV
      - name: Create docker image tags
        run: |
          echo "DOCKER_TAG=${{ env.DOCKER_IMAGE }}:${{ env.COMPLETE_TAG }}" >> $GITHUB_ENV
      - name: Build docker image
        working-directory: ./sanity
        run: docker build -t ${{ env.DOCKER_TAG }} .
      - name: Push docker image
        working-directory: ./sanity
        run: |
          docker push ${{ env.DOCKER_TAG }}
      - name: Create tag and release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.COMPLETE_TAG }}
          release_name: ${{ env.COMPLETE_TAG }}
          commitish: ${{ github.sha }}
      - name: Deploy til dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais/prod/sanity-studio-prod-gcp.yml
          CLUSTER: prod-gcp
          REF: ${{ github.sha }}
          PRINT_PAYLOAD: true
          IMAGE: ${{ env.DOCKER_TAG }}
